# Generated by Django 5.0.6 on 2024-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='any ISO 3166-1', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'apps:i18n:language:verbose',
                'verbose_name_plural': 'apps:i18n:verbose-plural',
                'db_table': 'i18n_language',
            },
        ),
    ]
