FROM python:3.12-slim

ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements/ /opt/app/requirements/

WORKDIR /opt/app/

RUN pip install --no-cache-dir --upgrade -r requirements/dev.txt

COPY ./src/ /opt/app/

CMD python manage.py test --settings=core.settings.test --noinput       