FROM python:3.12-slim

ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements/ /opt/app/requirements/

WORKDIR /opt/app/

RUN pip install --no-cache-dir --upgrade -r requirements/dev.txt

COPY . /opt/app/

CMD python src/manage.py migrate && \ 
    python src/manage.py runserver 0.0.0.0:8000