line-length = 120
indent-width = 4


[lint]
extend-select = [
    "E", # flake8
    "F", # Pyflakes
    "I", # isort
    "PL" # pylint
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[lint.isort]
force-single-line = true
order-by-type = false
required-imports = ["from __future__ import annotations"]