# Generated by Django 5.0.6 on 2024-05-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('i18n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'apps:i18n:locale:translation-key:verbose',
                'verbose_name_plural': 'apps:i18n:locale:translation-key:verbose-plural',
                'db_table': 'i18n_locale_translation_key',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i18n.language')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='locale.translationkey')),
            ],
            options={
                'verbose_name': 'apps:i18n:locale:translation:verbose',
                'verbose_name_plural': 'apps:i18n:locale:translation:verbose-plural',
                'db_table': 'i18n_locale_translation',
                'unique_together': {('key', 'language')},
            },
        ),
    ]
